---
name: 'Run retag-ecr-image action'

on:
  pull_request:
    paths:
      - actions/retag-ecr-image/*

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test-retag-ecr-image-action:
    name: 'Uses the retag-ecr-image action'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout actions'
        uses: actions/checkout@v5

      - name: 'Test retag-docker-image action'
        uses: ./.github/actions/test-retag-docker-image # we can reuse the same logic as the retag-docker-image action
        with:
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
